<a href="https://colab.research.google.com/github/ashikha-03/AI/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
mylist=[1,2,3]
mylist.append(4)
mylist.append(5)
mylist

[1, 2, 3, 4, 5]

In [ ]:
newlist=[6,7,8]
mylist.extend(newlist)
print(mylist)

[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
mylist.insert(0,"Hello")
print(mylist)

['Hello', 'Hello', 'Hello', 1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
mylist.remove(5)
print(mylist)

['Hello', 'Hello', 'Hello', 1, 2, 3, 4, 6, 7, 8]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(np.shape(arr))
print(type(arr))

(4,)
<class 'numpy.ndarray'>


In [ ]:
b=np.array([[1,2,3],[4,5,6,7]])
print(type(b))
print(np.shape(b))

<class 'numpy.ndarray'>
(2,)


<ipython-input-15-6113ec40611c>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b=np.array([[1,2,3],[4,5,6,7]])


In [ ]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(type(c))
print(np.shape(c))

<class 'numpy.ndarray'>
(3, 3)


In [ ]:
d=np.ones([4])
e=np.ones([3,3])
f=np.zeros([4])
g=np.random.random([4])
print(d)
print(e)
print(f)
print(g)

[1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0. 0. 0. 0.]
[0.38700515 0.85827747 0.78232026 0.96518882]


In [ ]:
h=np.ones([5,5,5,5,5])
print(h)

[[[[[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]]


  [[[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1.]
    [1. 1. 1. 

In [ ]:
i=np.eye(2)
print(i)

[[1. 0.]
 [0. 1.]]


In [ ]:
j=np.full((5,2,3),0)
print(j)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


In [ ]:
import numpy as np
a=np.arange(10,50,5)
print(a)

[10 15 20 25 30 35 40 45]


In [ ]:
a=np.linspace(0.,1.,num=5)
print(a)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
print(a)


[[1 2 3]
 [4 5 6]]


In [ ]:
a[0,1]

2

In [ ]:
a[0:2,0]

array([1, 4])

In [ ]:
np.shape(a)

(2, 3)

In [ ]:
a=np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
r1=a[1,:]
print(r1,r1.shape)

[1 2 3 4] (4,)


In [ ]:
a=np.array([[0,1,2,3],[0,1,2,3],[0,1,2,3],[0,1,2,3]])
print(a)


[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [ ]:
a=np.array({1,2,3,5,4,6,7,8,})
print(np.argmax(a)) #returns index of maximum number
print(np.argmin(a))
print(np.argsort(a))
print(np.argsort(a)[::-1])



3


In [ ]:
a=np.array([[3,2,1],[6,5,4],[9,8,7]])
print(a)
a=np.sort(a,axis=1,kind="quicksort")
print(a)

In [ ]:
%%time
x=np.sum(a)

CPU times: user 168 µs, sys: 36 µs, total: 204 µs
Wall time: 3.54 ms


In [ ]:
#broadcasting expand and work
a=np.array([1,2,3])
